package com.ahem.machine.pub.po;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table v_bet_statistic
 *
 * @mbg.generated do_not_delete_during_merge Wed Apr 19 09:59:47 CST 2017
 */
public class VBetStatistic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_bet_statistic.record_id
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_bet_statistic.fruit_id
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    private Integer fruitId;

    /**
     * Database Column Remarks:
     *   中文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_bet_statistic.fruit_name
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    private String fruitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_bet_statistic.sum_score
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    private BigDecimal sumScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_bet_statistic.all_sum
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    private BigDecimal allSum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_bet_statistic.record_id
     *
     * @return the value of v_bet_statistic.record_id
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_bet_statistic.record_id
     *
     * @param recordId the value for v_bet_statistic.record_id
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_bet_statistic.fruit_id
     *
     * @return the value of v_bet_statistic.fruit_id
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    public Integer getFruitId() {
        return fruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_bet_statistic.fruit_id
     *
     * @param fruitId the value for v_bet_statistic.fruit_id
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    public void setFruitId(Integer fruitId) {
        this.fruitId = fruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_bet_statistic.fruit_name
     *
     * @return the value of v_bet_statistic.fruit_name
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    public String getFruitName() {
        return fruitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_bet_statistic.fruit_name
     *
     * @param fruitName the value for v_bet_statistic.fruit_name
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    public void setFruitName(String fruitName) {
        this.fruitName = fruitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_bet_statistic.sum_score
     *
     * @return the value of v_bet_statistic.sum_score
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    public BigDecimal getSumScore() {
        return sumScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_bet_statistic.sum_score
     *
     * @param sumScore the value for v_bet_statistic.sum_score
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    public void setSumScore(BigDecimal sumScore) {
        this.sumScore = sumScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_bet_statistic.all_sum
     *
     * @return the value of v_bet_statistic.all_sum
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    public BigDecimal getAllSum() {
        return allSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_bet_statistic.all_sum
     *
     * @param allSum the value for v_bet_statistic.all_sum
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    public void setAllSum(BigDecimal allSum) {
        this.allSum = allSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_bet_statistic
     *
     * @mbg.generated Wed Apr 19 09:59:47 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recordId=").append(recordId);
        sb.append(", fruitId=").append(fruitId);
        sb.append(", fruitName=").append(fruitName);
        sb.append(", sumScore=").append(sumScore);
        sb.append(", allSum=").append(allSum);
        sb.append("]");
        return sb.toString();
    }
}