package com.ahem.machine.weixin.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_machine_user
 *
 * @mbg.generated do_not_delete_during_merge Sun Mar 26 16:59:34 CST 2017
 */
public class TMachineUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_user.id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 用户名 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_user.user_name
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_user.password
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private String password;
	/**
	 * Database Column Remarks: 手机号码 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_user.mobile_num
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Integer mobileNum;
	/**
	 * Database Column Remarks: 微信唯一标识id This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_user.weixin_open_id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private String weixinOpenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_user.create_time
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_user.login_time
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Date loginTime;
	/**
	 * Database Column Remarks: 分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_user.score
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Integer score;
	/**
	 * Database Column Remarks: 用户昵称 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_user.nickname
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private String nickname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_user.id
	 * @return  the value of t_machine_user.id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_user.id
	 * @param id  the value for t_machine_user.id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_user.user_name
	 * @return  the value of t_machine_user.user_name
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_user.user_name
	 * @param userName  the value for t_machine_user.user_name
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_user.password
	 * @return  the value of t_machine_user.password
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_user.password
	 * @param password  the value for t_machine_user.password
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_user.mobile_num
	 * @return  the value of t_machine_user.mobile_num
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Integer getMobileNum() {
		return mobileNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_user.mobile_num
	 * @param mobileNum  the value for t_machine_user.mobile_num
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setMobileNum(Integer mobileNum) {
		this.mobileNum = mobileNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_user.weixin_open_id
	 * @return  the value of t_machine_user.weixin_open_id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String getWeixinOpenId() {
		return weixinOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_user.weixin_open_id
	 * @param weixinOpenId  the value for t_machine_user.weixin_open_id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setWeixinOpenId(String weixinOpenId) {
		this.weixinOpenId = weixinOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_user.create_time
	 * @return  the value of t_machine_user.create_time
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_user.create_time
	 * @param createTime  the value for t_machine_user.create_time
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_user.login_time
	 * @return  the value of t_machine_user.login_time
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Date getLoginTime() {
		return loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_user.login_time
	 * @param loginTime  the value for t_machine_user.login_time
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_user.score
	 * @return  the value of t_machine_user.score
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_user.score
	 * @param score  the value for t_machine_user.score
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_user.nickname
	 * @return  the value of t_machine_user.nickname
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_user.nickname
	 * @param nickname  the value for t_machine_user.nickname
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_user
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", userName=").append(userName);
		sb.append(", password=").append(password);
		sb.append(", mobileNum=").append(mobileNum);
		sb.append(", weixinOpenId=").append(weixinOpenId);
		sb.append(", createTime=").append(createTime);
		sb.append(", loginTime=").append(loginTime);
		sb.append(", score=").append(score);
		sb.append(", nickname=").append(nickname);
		sb.append("]");
		return sb.toString();
	}
}