package com.ahem.machine.weixin.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_machine_big_small_record
 *
 * @mbg.generated do_not_delete_during_merge Sat Apr 15 20:11:49 CST 2017
 */
public class TMachineBigSmallRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_big_small_record.id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 期号 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_big_small_record.record_id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Integer recordId;
	/**
	 * Database Column Remarks: 用户id This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_big_small_record.user_id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Integer userId;
	/**
	 * Database Column Remarks: 1大0小 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_big_small_record.big_small_num
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Integer bigSmallNum;
	/**
	 * Database Column Remarks: 0小1大 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_big_small_record.bet_num
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Integer betNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_big_small_record.bet_time
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Date betTime;
	/**
	 * Database Column Remarks: 下注分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_big_small_record.bet_score
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Integer betScore;
	/**
	 * Database Column Remarks: 获奖分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_big_small_record.got_score
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	private Integer gotScore;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_big_small_record.id
	 * @return  the value of t_machine_big_small_record.id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_big_small_record.id
	 * @param id  the value for t_machine_big_small_record.id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_big_small_record.record_id
	 * @return  the value of t_machine_big_small_record.record_id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Integer getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_big_small_record.record_id
	 * @param recordId  the value for t_machine_big_small_record.record_id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_big_small_record.user_id
	 * @return  the value of t_machine_big_small_record.user_id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_big_small_record.user_id
	 * @param userId  the value for t_machine_big_small_record.user_id
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_big_small_record.big_small_num
	 * @return  the value of t_machine_big_small_record.big_small_num
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Integer getBigSmallNum() {
		return bigSmallNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_big_small_record.big_small_num
	 * @param bigSmallNum  the value for t_machine_big_small_record.big_small_num
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setBigSmallNum(Integer bigSmallNum) {
		this.bigSmallNum = bigSmallNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_big_small_record.bet_num
	 * @return  the value of t_machine_big_small_record.bet_num
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Integer getBetNum() {
		return betNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_big_small_record.bet_num
	 * @param betNum  the value for t_machine_big_small_record.bet_num
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setBetNum(Integer betNum) {
		this.betNum = betNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_big_small_record.bet_time
	 * @return  the value of t_machine_big_small_record.bet_time
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Date getBetTime() {
		return betTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_big_small_record.bet_time
	 * @param betTime  the value for t_machine_big_small_record.bet_time
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setBetTime(Date betTime) {
		this.betTime = betTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_big_small_record.bet_score
	 * @return  the value of t_machine_big_small_record.bet_score
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Integer getBetScore() {
		return betScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_big_small_record.bet_score
	 * @param betScore  the value for t_machine_big_small_record.bet_score
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setBetScore(Integer betScore) {
		this.betScore = betScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_big_small_record.got_score
	 * @return  the value of t_machine_big_small_record.got_score
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Integer getGotScore() {
		return gotScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_big_small_record.got_score
	 * @param gotScore  the value for t_machine_big_small_record.got_score
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setGotScore(Integer gotScore) {
		this.gotScore = gotScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", recordId=").append(recordId);
		sb.append(", userId=").append(userId);
		sb.append(", bigSmallNum=").append(bigSmallNum);
		sb.append(", betNum=").append(betNum);
		sb.append(", betTime=").append(betTime);
		sb.append(", betScore=").append(betScore);
		sb.append(", gotScore=").append(gotScore);
		sb.append("]");
		return sb.toString();
	}
}