package com.ahem.machine.weixin.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_machine_bet_record
 *
 * @mbg.generated do_not_delete_during_merge Sun Mar 26 16:59:34 CST 2017
 */
public class TMachineBetRecord {

	/**
	 * Database Column Remarks: 下注id This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.id
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 用户编号 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.user_id
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer userId;
	/**
	 * Database Column Remarks: 开奖期号 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.record_id
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer recordId;
	/**
	 * Database Column Remarks: 下注倍数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_multiple
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betMultiple;
	/**
	 * Database Column Remarks: 下注时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_time
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Date betTime;
	/**
	 * Database Column Remarks: 下注水果编号 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_fruit_id_1
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betFruitId1;
	/**
	 * Database Column Remarks: 下注分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_score_1
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betScore1;
	/**
	 * Database Column Remarks: 下注水果编号 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_fruit_id_2
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betFruitId2;
	/**
	 * Database Column Remarks: 下注分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_score_2
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betScore2;
	/**
	 * Database Column Remarks: 下注水果编号 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_fruit_id_3
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betFruitId3;
	/**
	 * Database Column Remarks: 下注分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_score_3
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betScore3;
	/**
	 * Database Column Remarks: 下注水果编号 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_fruit_id_4
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betFruitId4;
	/**
	 * Database Column Remarks: 下注分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_score_4
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betScore4;
	/**
	 * Database Column Remarks: 下注水果编号 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_fruit_id_5
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betFruitId5;
	/**
	 * Database Column Remarks: 下注分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_score_5
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betScore5;
	/**
	 * Database Column Remarks: 下注水果编号 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_fruit_id_6
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betFruitId6;
	/**
	 * Database Column Remarks: 下注分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_score_6
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betScore6;
	/**
	 * Database Column Remarks: 下注水果编号 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_fruit_id_7
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betFruitId7;
	/**
	 * Database Column Remarks: 下注分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_score_7
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betScore7;
	/**
	 * Database Column Remarks: 0输1赢2平 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.bet_result
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer betResult;
	/**
	 * Database Column Remarks: 获得的分数 This field was generated by MyBatis Generator. This field corresponds to the database column t_machine_bet_record.got_score
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	private Integer gotScore;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.id
	 * @return  the value of t_machine_bet_record.id
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.id
	 * @param id  the value for t_machine_bet_record.id
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.user_id
	 * @return  the value of t_machine_bet_record.user_id
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.user_id
	 * @param userId  the value for t_machine_bet_record.user_id
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.record_id
	 * @return  the value of t_machine_bet_record.record_id
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.record_id
	 * @param recordId  the value for t_machine_bet_record.record_id
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_multiple
	 * @return  the value of t_machine_bet_record.bet_multiple
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetMultiple() {
		return betMultiple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_multiple
	 * @param betMultiple  the value for t_machine_bet_record.bet_multiple
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetMultiple(Integer betMultiple) {
		this.betMultiple = betMultiple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_time
	 * @return  the value of t_machine_bet_record.bet_time
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Date getBetTime() {
		return betTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_time
	 * @param betTime  the value for t_machine_bet_record.bet_time
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetTime(Date betTime) {
		this.betTime = betTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_fruit_id_1
	 * @return  the value of t_machine_bet_record.bet_fruit_id_1
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetFruitId1() {
		return betFruitId1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_fruit_id_1
	 * @param betFruitId1  the value for t_machine_bet_record.bet_fruit_id_1
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetFruitId1(Integer betFruitId1) {
		this.betFruitId1 = betFruitId1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_score_1
	 * @return  the value of t_machine_bet_record.bet_score_1
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetScore1() {
		return betScore1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_score_1
	 * @param betScore1  the value for t_machine_bet_record.bet_score_1
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetScore1(Integer betScore1) {
		this.betScore1 = betScore1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_fruit_id_2
	 * @return  the value of t_machine_bet_record.bet_fruit_id_2
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetFruitId2() {
		return betFruitId2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_fruit_id_2
	 * @param betFruitId2  the value for t_machine_bet_record.bet_fruit_id_2
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetFruitId2(Integer betFruitId2) {
		this.betFruitId2 = betFruitId2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_score_2
	 * @return  the value of t_machine_bet_record.bet_score_2
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetScore2() {
		return betScore2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_score_2
	 * @param betScore2  the value for t_machine_bet_record.bet_score_2
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetScore2(Integer betScore2) {
		this.betScore2 = betScore2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_fruit_id_3
	 * @return  the value of t_machine_bet_record.bet_fruit_id_3
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetFruitId3() {
		return betFruitId3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_fruit_id_3
	 * @param betFruitId3  the value for t_machine_bet_record.bet_fruit_id_3
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetFruitId3(Integer betFruitId3) {
		this.betFruitId3 = betFruitId3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_score_3
	 * @return  the value of t_machine_bet_record.bet_score_3
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetScore3() {
		return betScore3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_score_3
	 * @param betScore3  the value for t_machine_bet_record.bet_score_3
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetScore3(Integer betScore3) {
		this.betScore3 = betScore3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_fruit_id_4
	 * @return  the value of t_machine_bet_record.bet_fruit_id_4
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetFruitId4() {
		return betFruitId4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_fruit_id_4
	 * @param betFruitId4  the value for t_machine_bet_record.bet_fruit_id_4
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetFruitId4(Integer betFruitId4) {
		this.betFruitId4 = betFruitId4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_score_4
	 * @return  the value of t_machine_bet_record.bet_score_4
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetScore4() {
		return betScore4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_score_4
	 * @param betScore4  the value for t_machine_bet_record.bet_score_4
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetScore4(Integer betScore4) {
		this.betScore4 = betScore4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_fruit_id_5
	 * @return  the value of t_machine_bet_record.bet_fruit_id_5
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetFruitId5() {
		return betFruitId5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_fruit_id_5
	 * @param betFruitId5  the value for t_machine_bet_record.bet_fruit_id_5
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetFruitId5(Integer betFruitId5) {
		this.betFruitId5 = betFruitId5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_score_5
	 * @return  the value of t_machine_bet_record.bet_score_5
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetScore5() {
		return betScore5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_score_5
	 * @param betScore5  the value for t_machine_bet_record.bet_score_5
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetScore5(Integer betScore5) {
		this.betScore5 = betScore5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_fruit_id_6
	 * @return  the value of t_machine_bet_record.bet_fruit_id_6
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetFruitId6() {
		return betFruitId6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_fruit_id_6
	 * @param betFruitId6  the value for t_machine_bet_record.bet_fruit_id_6
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetFruitId6(Integer betFruitId6) {
		this.betFruitId6 = betFruitId6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_score_6
	 * @return  the value of t_machine_bet_record.bet_score_6
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetScore6() {
		return betScore6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_score_6
	 * @param betScore6  the value for t_machine_bet_record.bet_score_6
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetScore6(Integer betScore6) {
		this.betScore6 = betScore6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_fruit_id_7
	 * @return  the value of t_machine_bet_record.bet_fruit_id_7
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetFruitId7() {
		return betFruitId7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_fruit_id_7
	 * @param betFruitId7  the value for t_machine_bet_record.bet_fruit_id_7
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetFruitId7(Integer betFruitId7) {
		this.betFruitId7 = betFruitId7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_score_7
	 * @return  the value of t_machine_bet_record.bet_score_7
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetScore7() {
		return betScore7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_score_7
	 * @param betScore7  the value for t_machine_bet_record.bet_score_7
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetScore7(Integer betScore7) {
		this.betScore7 = betScore7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.bet_result
	 * @return  the value of t_machine_bet_record.bet_result
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getBetResult() {
		return betResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.bet_result
	 * @param betResult  the value for t_machine_bet_record.bet_result
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setBetResult(Integer betResult) {
		this.betResult = betResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_machine_bet_record.got_score
	 * @return  the value of t_machine_bet_record.got_score
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public Integer getGotScore() {
		return gotScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_machine_bet_record.got_score
	 * @param gotScore  the value for t_machine_bet_record.got_score
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	public void setGotScore(Integer gotScore) {
		this.gotScore = gotScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", userId=").append(userId);
		sb.append(", recordId=").append(recordId);
		sb.append(", betMultiple=").append(betMultiple);
		sb.append(", betTime=").append(betTime);
		sb.append(", betFruitId1=").append(betFruitId1);
		sb.append(", betScore1=").append(betScore1);
		sb.append(", betFruitId2=").append(betFruitId2);
		sb.append(", betScore2=").append(betScore2);
		sb.append(", betFruitId3=").append(betFruitId3);
		sb.append(", betScore3=").append(betScore3);
		sb.append(", betFruitId4=").append(betFruitId4);
		sb.append(", betScore4=").append(betScore4);
		sb.append(", betFruitId5=").append(betFruitId5);
		sb.append(", betScore5=").append(betScore5);
		sb.append(", betFruitId6=").append(betFruitId6);
		sb.append(", betScore6=").append(betScore6);
		sb.append(", betFruitId7=").append(betFruitId7);
		sb.append(", betScore7=").append(betScore7);
		sb.append(", betResult=").append(betResult);
		sb.append(", gotScore=").append(gotScore);
		sb.append("]");
		return sb.toString();
	}
}