package com.ahem.machine.weixin.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMachineBigSmallRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public TMachineBigSmallRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNull() {
			addCriterion("record_id is null");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNotNull() {
			addCriterion("record_id is not null");
			return (Criteria) this;
		}

		public Criteria andRecordIdEqualTo(Integer value) {
			addCriterion("record_id =", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotEqualTo(Integer value) {
			addCriterion("record_id <>", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThan(Integer value) {
			addCriterion("record_id >", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("record_id >=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThan(Integer value) {
			addCriterion("record_id <", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThanOrEqualTo(Integer value) {
			addCriterion("record_id <=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdIn(List<Integer> values) {
			addCriterion("record_id in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotIn(List<Integer> values) {
			addCriterion("record_id not in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdBetween(Integer value1, Integer value2) {
			addCriterion("record_id between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotBetween(Integer value1, Integer value2) {
			addCriterion("record_id not between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumIsNull() {
			addCriterion("big_small_num is null");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumIsNotNull() {
			addCriterion("big_small_num is not null");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumEqualTo(Integer value) {
			addCriterion("big_small_num =", value, "bigSmallNum");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumNotEqualTo(Integer value) {
			addCriterion("big_small_num <>", value, "bigSmallNum");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumGreaterThan(Integer value) {
			addCriterion("big_small_num >", value, "bigSmallNum");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("big_small_num >=", value, "bigSmallNum");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumLessThan(Integer value) {
			addCriterion("big_small_num <", value, "bigSmallNum");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumLessThanOrEqualTo(Integer value) {
			addCriterion("big_small_num <=", value, "bigSmallNum");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumIn(List<Integer> values) {
			addCriterion("big_small_num in", values, "bigSmallNum");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumNotIn(List<Integer> values) {
			addCriterion("big_small_num not in", values, "bigSmallNum");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumBetween(Integer value1, Integer value2) {
			addCriterion("big_small_num between", value1, value2, "bigSmallNum");
			return (Criteria) this;
		}

		public Criteria andBigSmallNumNotBetween(Integer value1, Integer value2) {
			addCriterion("big_small_num not between", value1, value2, "bigSmallNum");
			return (Criteria) this;
		}

		public Criteria andBetNumIsNull() {
			addCriterion("bet_num is null");
			return (Criteria) this;
		}

		public Criteria andBetNumIsNotNull() {
			addCriterion("bet_num is not null");
			return (Criteria) this;
		}

		public Criteria andBetNumEqualTo(Integer value) {
			addCriterion("bet_num =", value, "betNum");
			return (Criteria) this;
		}

		public Criteria andBetNumNotEqualTo(Integer value) {
			addCriterion("bet_num <>", value, "betNum");
			return (Criteria) this;
		}

		public Criteria andBetNumGreaterThan(Integer value) {
			addCriterion("bet_num >", value, "betNum");
			return (Criteria) this;
		}

		public Criteria andBetNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_num >=", value, "betNum");
			return (Criteria) this;
		}

		public Criteria andBetNumLessThan(Integer value) {
			addCriterion("bet_num <", value, "betNum");
			return (Criteria) this;
		}

		public Criteria andBetNumLessThanOrEqualTo(Integer value) {
			addCriterion("bet_num <=", value, "betNum");
			return (Criteria) this;
		}

		public Criteria andBetNumIn(List<Integer> values) {
			addCriterion("bet_num in", values, "betNum");
			return (Criteria) this;
		}

		public Criteria andBetNumNotIn(List<Integer> values) {
			addCriterion("bet_num not in", values, "betNum");
			return (Criteria) this;
		}

		public Criteria andBetNumBetween(Integer value1, Integer value2) {
			addCriterion("bet_num between", value1, value2, "betNum");
			return (Criteria) this;
		}

		public Criteria andBetNumNotBetween(Integer value1, Integer value2) {
			addCriterion("bet_num not between", value1, value2, "betNum");
			return (Criteria) this;
		}

		public Criteria andBetTimeIsNull() {
			addCriterion("bet_time is null");
			return (Criteria) this;
		}

		public Criteria andBetTimeIsNotNull() {
			addCriterion("bet_time is not null");
			return (Criteria) this;
		}

		public Criteria andBetTimeEqualTo(Date value) {
			addCriterion("bet_time =", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeNotEqualTo(Date value) {
			addCriterion("bet_time <>", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeGreaterThan(Date value) {
			addCriterion("bet_time >", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("bet_time >=", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeLessThan(Date value) {
			addCriterion("bet_time <", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeLessThanOrEqualTo(Date value) {
			addCriterion("bet_time <=", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeIn(List<Date> values) {
			addCriterion("bet_time in", values, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeNotIn(List<Date> values) {
			addCriterion("bet_time not in", values, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeBetween(Date value1, Date value2) {
			addCriterion("bet_time between", value1, value2, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeNotBetween(Date value1, Date value2) {
			addCriterion("bet_time not between", value1, value2, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetScoreIsNull() {
			addCriterion("bet_score is null");
			return (Criteria) this;
		}

		public Criteria andBetScoreIsNotNull() {
			addCriterion("bet_score is not null");
			return (Criteria) this;
		}

		public Criteria andBetScoreEqualTo(Integer value) {
			addCriterion("bet_score =", value, "betScore");
			return (Criteria) this;
		}

		public Criteria andBetScoreNotEqualTo(Integer value) {
			addCriterion("bet_score <>", value, "betScore");
			return (Criteria) this;
		}

		public Criteria andBetScoreGreaterThan(Integer value) {
			addCriterion("bet_score >", value, "betScore");
			return (Criteria) this;
		}

		public Criteria andBetScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_score >=", value, "betScore");
			return (Criteria) this;
		}

		public Criteria andBetScoreLessThan(Integer value) {
			addCriterion("bet_score <", value, "betScore");
			return (Criteria) this;
		}

		public Criteria andBetScoreLessThanOrEqualTo(Integer value) {
			addCriterion("bet_score <=", value, "betScore");
			return (Criteria) this;
		}

		public Criteria andBetScoreIn(List<Integer> values) {
			addCriterion("bet_score in", values, "betScore");
			return (Criteria) this;
		}

		public Criteria andBetScoreNotIn(List<Integer> values) {
			addCriterion("bet_score not in", values, "betScore");
			return (Criteria) this;
		}

		public Criteria andBetScoreBetween(Integer value1, Integer value2) {
			addCriterion("bet_score between", value1, value2, "betScore");
			return (Criteria) this;
		}

		public Criteria andBetScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("bet_score not between", value1, value2, "betScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreIsNull() {
			addCriterion("got_score is null");
			return (Criteria) this;
		}

		public Criteria andGotScoreIsNotNull() {
			addCriterion("got_score is not null");
			return (Criteria) this;
		}

		public Criteria andGotScoreEqualTo(Integer value) {
			addCriterion("got_score =", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreNotEqualTo(Integer value) {
			addCriterion("got_score <>", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreGreaterThan(Integer value) {
			addCriterion("got_score >", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("got_score >=", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreLessThan(Integer value) {
			addCriterion("got_score <", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreLessThanOrEqualTo(Integer value) {
			addCriterion("got_score <=", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreIn(List<Integer> values) {
			addCriterion("got_score in", values, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreNotIn(List<Integer> values) {
			addCriterion("got_score not in", values, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreBetween(Integer value1, Integer value2) {
			addCriterion("got_score between", value1, value2, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("got_score not between", value1, value2, "gotScore");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_machine_big_small_record
     *
     * @mbg.generated do_not_delete_during_merge Sat Apr 15 20:11:49 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}