package com.ahem.machine.weixin.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TMachineBetRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public TMachineBetRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNull() {
			addCriterion("record_id is null");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNotNull() {
			addCriterion("record_id is not null");
			return (Criteria) this;
		}

		public Criteria andRecordIdEqualTo(Integer value) {
			addCriterion("record_id =", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotEqualTo(Integer value) {
			addCriterion("record_id <>", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThan(Integer value) {
			addCriterion("record_id >", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("record_id >=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThan(Integer value) {
			addCriterion("record_id <", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThanOrEqualTo(Integer value) {
			addCriterion("record_id <=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdIn(List<Integer> values) {
			addCriterion("record_id in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotIn(List<Integer> values) {
			addCriterion("record_id not in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdBetween(Integer value1, Integer value2) {
			addCriterion("record_id between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotBetween(Integer value1, Integer value2) {
			addCriterion("record_id not between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andBetMultipleIsNull() {
			addCriterion("bet_multiple is null");
			return (Criteria) this;
		}

		public Criteria andBetMultipleIsNotNull() {
			addCriterion("bet_multiple is not null");
			return (Criteria) this;
		}

		public Criteria andBetMultipleEqualTo(Integer value) {
			addCriterion("bet_multiple =", value, "betMultiple");
			return (Criteria) this;
		}

		public Criteria andBetMultipleNotEqualTo(Integer value) {
			addCriterion("bet_multiple <>", value, "betMultiple");
			return (Criteria) this;
		}

		public Criteria andBetMultipleGreaterThan(Integer value) {
			addCriterion("bet_multiple >", value, "betMultiple");
			return (Criteria) this;
		}

		public Criteria andBetMultipleGreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_multiple >=", value, "betMultiple");
			return (Criteria) this;
		}

		public Criteria andBetMultipleLessThan(Integer value) {
			addCriterion("bet_multiple <", value, "betMultiple");
			return (Criteria) this;
		}

		public Criteria andBetMultipleLessThanOrEqualTo(Integer value) {
			addCriterion("bet_multiple <=", value, "betMultiple");
			return (Criteria) this;
		}

		public Criteria andBetMultipleIn(List<Integer> values) {
			addCriterion("bet_multiple in", values, "betMultiple");
			return (Criteria) this;
		}

		public Criteria andBetMultipleNotIn(List<Integer> values) {
			addCriterion("bet_multiple not in", values, "betMultiple");
			return (Criteria) this;
		}

		public Criteria andBetMultipleBetween(Integer value1, Integer value2) {
			addCriterion("bet_multiple between", value1, value2, "betMultiple");
			return (Criteria) this;
		}

		public Criteria andBetMultipleNotBetween(Integer value1, Integer value2) {
			addCriterion("bet_multiple not between", value1, value2, "betMultiple");
			return (Criteria) this;
		}

		public Criteria andBetTimeIsNull() {
			addCriterion("bet_time is null");
			return (Criteria) this;
		}

		public Criteria andBetTimeIsNotNull() {
			addCriterion("bet_time is not null");
			return (Criteria) this;
		}

		public Criteria andBetTimeEqualTo(Date value) {
			addCriterion("bet_time =", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeNotEqualTo(Date value) {
			addCriterion("bet_time <>", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeGreaterThan(Date value) {
			addCriterion("bet_time >", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("bet_time >=", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeLessThan(Date value) {
			addCriterion("bet_time <", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeLessThanOrEqualTo(Date value) {
			addCriterion("bet_time <=", value, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeIn(List<Date> values) {
			addCriterion("bet_time in", values, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeNotIn(List<Date> values) {
			addCriterion("bet_time not in", values, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeBetween(Date value1, Date value2) {
			addCriterion("bet_time between", value1, value2, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetTimeNotBetween(Date value1, Date value2) {
			addCriterion("bet_time not between", value1, value2, "betTime");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1IsNull() {
			addCriterion("bet_fruit_id_1 is null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1IsNotNull() {
			addCriterion("bet_fruit_id_1 is not null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1EqualTo(Integer value) {
			addCriterion("bet_fruit_id_1 =", value, "betFruitId1");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1NotEqualTo(Integer value) {
			addCriterion("bet_fruit_id_1 <>", value, "betFruitId1");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1GreaterThan(Integer value) {
			addCriterion("bet_fruit_id_1 >", value, "betFruitId1");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_1 >=", value, "betFruitId1");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1LessThan(Integer value) {
			addCriterion("bet_fruit_id_1 <", value, "betFruitId1");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1LessThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_1 <=", value, "betFruitId1");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1In(List<Integer> values) {
			addCriterion("bet_fruit_id_1 in", values, "betFruitId1");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1NotIn(List<Integer> values) {
			addCriterion("bet_fruit_id_1 not in", values, "betFruitId1");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1Between(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_1 between", value1, value2, "betFruitId1");
			return (Criteria) this;
		}

		public Criteria andBetFruitId1NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_1 not between", value1, value2, "betFruitId1");
			return (Criteria) this;
		}

		public Criteria andBetScore1IsNull() {
			addCriterion("bet_score_1 is null");
			return (Criteria) this;
		}

		public Criteria andBetScore1IsNotNull() {
			addCriterion("bet_score_1 is not null");
			return (Criteria) this;
		}

		public Criteria andBetScore1EqualTo(Integer value) {
			addCriterion("bet_score_1 =", value, "betScore1");
			return (Criteria) this;
		}

		public Criteria andBetScore1NotEqualTo(Integer value) {
			addCriterion("bet_score_1 <>", value, "betScore1");
			return (Criteria) this;
		}

		public Criteria andBetScore1GreaterThan(Integer value) {
			addCriterion("bet_score_1 >", value, "betScore1");
			return (Criteria) this;
		}

		public Criteria andBetScore1GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_score_1 >=", value, "betScore1");
			return (Criteria) this;
		}

		public Criteria andBetScore1LessThan(Integer value) {
			addCriterion("bet_score_1 <", value, "betScore1");
			return (Criteria) this;
		}

		public Criteria andBetScore1LessThanOrEqualTo(Integer value) {
			addCriterion("bet_score_1 <=", value, "betScore1");
			return (Criteria) this;
		}

		public Criteria andBetScore1In(List<Integer> values) {
			addCriterion("bet_score_1 in", values, "betScore1");
			return (Criteria) this;
		}

		public Criteria andBetScore1NotIn(List<Integer> values) {
			addCriterion("bet_score_1 not in", values, "betScore1");
			return (Criteria) this;
		}

		public Criteria andBetScore1Between(Integer value1, Integer value2) {
			addCriterion("bet_score_1 between", value1, value2, "betScore1");
			return (Criteria) this;
		}

		public Criteria andBetScore1NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_score_1 not between", value1, value2, "betScore1");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2IsNull() {
			addCriterion("bet_fruit_id_2 is null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2IsNotNull() {
			addCriterion("bet_fruit_id_2 is not null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2EqualTo(Integer value) {
			addCriterion("bet_fruit_id_2 =", value, "betFruitId2");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2NotEqualTo(Integer value) {
			addCriterion("bet_fruit_id_2 <>", value, "betFruitId2");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2GreaterThan(Integer value) {
			addCriterion("bet_fruit_id_2 >", value, "betFruitId2");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_2 >=", value, "betFruitId2");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2LessThan(Integer value) {
			addCriterion("bet_fruit_id_2 <", value, "betFruitId2");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2LessThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_2 <=", value, "betFruitId2");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2In(List<Integer> values) {
			addCriterion("bet_fruit_id_2 in", values, "betFruitId2");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2NotIn(List<Integer> values) {
			addCriterion("bet_fruit_id_2 not in", values, "betFruitId2");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2Between(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_2 between", value1, value2, "betFruitId2");
			return (Criteria) this;
		}

		public Criteria andBetFruitId2NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_2 not between", value1, value2, "betFruitId2");
			return (Criteria) this;
		}

		public Criteria andBetScore2IsNull() {
			addCriterion("bet_score_2 is null");
			return (Criteria) this;
		}

		public Criteria andBetScore2IsNotNull() {
			addCriterion("bet_score_2 is not null");
			return (Criteria) this;
		}

		public Criteria andBetScore2EqualTo(Integer value) {
			addCriterion("bet_score_2 =", value, "betScore2");
			return (Criteria) this;
		}

		public Criteria andBetScore2NotEqualTo(Integer value) {
			addCriterion("bet_score_2 <>", value, "betScore2");
			return (Criteria) this;
		}

		public Criteria andBetScore2GreaterThan(Integer value) {
			addCriterion("bet_score_2 >", value, "betScore2");
			return (Criteria) this;
		}

		public Criteria andBetScore2GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_score_2 >=", value, "betScore2");
			return (Criteria) this;
		}

		public Criteria andBetScore2LessThan(Integer value) {
			addCriterion("bet_score_2 <", value, "betScore2");
			return (Criteria) this;
		}

		public Criteria andBetScore2LessThanOrEqualTo(Integer value) {
			addCriterion("bet_score_2 <=", value, "betScore2");
			return (Criteria) this;
		}

		public Criteria andBetScore2In(List<Integer> values) {
			addCriterion("bet_score_2 in", values, "betScore2");
			return (Criteria) this;
		}

		public Criteria andBetScore2NotIn(List<Integer> values) {
			addCriterion("bet_score_2 not in", values, "betScore2");
			return (Criteria) this;
		}

		public Criteria andBetScore2Between(Integer value1, Integer value2) {
			addCriterion("bet_score_2 between", value1, value2, "betScore2");
			return (Criteria) this;
		}

		public Criteria andBetScore2NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_score_2 not between", value1, value2, "betScore2");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3IsNull() {
			addCriterion("bet_fruit_id_3 is null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3IsNotNull() {
			addCriterion("bet_fruit_id_3 is not null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3EqualTo(Integer value) {
			addCriterion("bet_fruit_id_3 =", value, "betFruitId3");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3NotEqualTo(Integer value) {
			addCriterion("bet_fruit_id_3 <>", value, "betFruitId3");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3GreaterThan(Integer value) {
			addCriterion("bet_fruit_id_3 >", value, "betFruitId3");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_3 >=", value, "betFruitId3");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3LessThan(Integer value) {
			addCriterion("bet_fruit_id_3 <", value, "betFruitId3");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3LessThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_3 <=", value, "betFruitId3");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3In(List<Integer> values) {
			addCriterion("bet_fruit_id_3 in", values, "betFruitId3");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3NotIn(List<Integer> values) {
			addCriterion("bet_fruit_id_3 not in", values, "betFruitId3");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3Between(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_3 between", value1, value2, "betFruitId3");
			return (Criteria) this;
		}

		public Criteria andBetFruitId3NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_3 not between", value1, value2, "betFruitId3");
			return (Criteria) this;
		}

		public Criteria andBetScore3IsNull() {
			addCriterion("bet_score_3 is null");
			return (Criteria) this;
		}

		public Criteria andBetScore3IsNotNull() {
			addCriterion("bet_score_3 is not null");
			return (Criteria) this;
		}

		public Criteria andBetScore3EqualTo(Integer value) {
			addCriterion("bet_score_3 =", value, "betScore3");
			return (Criteria) this;
		}

		public Criteria andBetScore3NotEqualTo(Integer value) {
			addCriterion("bet_score_3 <>", value, "betScore3");
			return (Criteria) this;
		}

		public Criteria andBetScore3GreaterThan(Integer value) {
			addCriterion("bet_score_3 >", value, "betScore3");
			return (Criteria) this;
		}

		public Criteria andBetScore3GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_score_3 >=", value, "betScore3");
			return (Criteria) this;
		}

		public Criteria andBetScore3LessThan(Integer value) {
			addCriterion("bet_score_3 <", value, "betScore3");
			return (Criteria) this;
		}

		public Criteria andBetScore3LessThanOrEqualTo(Integer value) {
			addCriterion("bet_score_3 <=", value, "betScore3");
			return (Criteria) this;
		}

		public Criteria andBetScore3In(List<Integer> values) {
			addCriterion("bet_score_3 in", values, "betScore3");
			return (Criteria) this;
		}

		public Criteria andBetScore3NotIn(List<Integer> values) {
			addCriterion("bet_score_3 not in", values, "betScore3");
			return (Criteria) this;
		}

		public Criteria andBetScore3Between(Integer value1, Integer value2) {
			addCriterion("bet_score_3 between", value1, value2, "betScore3");
			return (Criteria) this;
		}

		public Criteria andBetScore3NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_score_3 not between", value1, value2, "betScore3");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4IsNull() {
			addCriterion("bet_fruit_id_4 is null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4IsNotNull() {
			addCriterion("bet_fruit_id_4 is not null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4EqualTo(Integer value) {
			addCriterion("bet_fruit_id_4 =", value, "betFruitId4");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4NotEqualTo(Integer value) {
			addCriterion("bet_fruit_id_4 <>", value, "betFruitId4");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4GreaterThan(Integer value) {
			addCriterion("bet_fruit_id_4 >", value, "betFruitId4");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_4 >=", value, "betFruitId4");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4LessThan(Integer value) {
			addCriterion("bet_fruit_id_4 <", value, "betFruitId4");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4LessThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_4 <=", value, "betFruitId4");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4In(List<Integer> values) {
			addCriterion("bet_fruit_id_4 in", values, "betFruitId4");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4NotIn(List<Integer> values) {
			addCriterion("bet_fruit_id_4 not in", values, "betFruitId4");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4Between(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_4 between", value1, value2, "betFruitId4");
			return (Criteria) this;
		}

		public Criteria andBetFruitId4NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_4 not between", value1, value2, "betFruitId4");
			return (Criteria) this;
		}

		public Criteria andBetScore4IsNull() {
			addCriterion("bet_score_4 is null");
			return (Criteria) this;
		}

		public Criteria andBetScore4IsNotNull() {
			addCriterion("bet_score_4 is not null");
			return (Criteria) this;
		}

		public Criteria andBetScore4EqualTo(Integer value) {
			addCriterion("bet_score_4 =", value, "betScore4");
			return (Criteria) this;
		}

		public Criteria andBetScore4NotEqualTo(Integer value) {
			addCriterion("bet_score_4 <>", value, "betScore4");
			return (Criteria) this;
		}

		public Criteria andBetScore4GreaterThan(Integer value) {
			addCriterion("bet_score_4 >", value, "betScore4");
			return (Criteria) this;
		}

		public Criteria andBetScore4GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_score_4 >=", value, "betScore4");
			return (Criteria) this;
		}

		public Criteria andBetScore4LessThan(Integer value) {
			addCriterion("bet_score_4 <", value, "betScore4");
			return (Criteria) this;
		}

		public Criteria andBetScore4LessThanOrEqualTo(Integer value) {
			addCriterion("bet_score_4 <=", value, "betScore4");
			return (Criteria) this;
		}

		public Criteria andBetScore4In(List<Integer> values) {
			addCriterion("bet_score_4 in", values, "betScore4");
			return (Criteria) this;
		}

		public Criteria andBetScore4NotIn(List<Integer> values) {
			addCriterion("bet_score_4 not in", values, "betScore4");
			return (Criteria) this;
		}

		public Criteria andBetScore4Between(Integer value1, Integer value2) {
			addCriterion("bet_score_4 between", value1, value2, "betScore4");
			return (Criteria) this;
		}

		public Criteria andBetScore4NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_score_4 not between", value1, value2, "betScore4");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5IsNull() {
			addCriterion("bet_fruit_id_5 is null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5IsNotNull() {
			addCriterion("bet_fruit_id_5 is not null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5EqualTo(Integer value) {
			addCriterion("bet_fruit_id_5 =", value, "betFruitId5");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5NotEqualTo(Integer value) {
			addCriterion("bet_fruit_id_5 <>", value, "betFruitId5");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5GreaterThan(Integer value) {
			addCriterion("bet_fruit_id_5 >", value, "betFruitId5");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_5 >=", value, "betFruitId5");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5LessThan(Integer value) {
			addCriterion("bet_fruit_id_5 <", value, "betFruitId5");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5LessThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_5 <=", value, "betFruitId5");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5In(List<Integer> values) {
			addCriterion("bet_fruit_id_5 in", values, "betFruitId5");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5NotIn(List<Integer> values) {
			addCriterion("bet_fruit_id_5 not in", values, "betFruitId5");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5Between(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_5 between", value1, value2, "betFruitId5");
			return (Criteria) this;
		}

		public Criteria andBetFruitId5NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_5 not between", value1, value2, "betFruitId5");
			return (Criteria) this;
		}

		public Criteria andBetScore5IsNull() {
			addCriterion("bet_score_5 is null");
			return (Criteria) this;
		}

		public Criteria andBetScore5IsNotNull() {
			addCriterion("bet_score_5 is not null");
			return (Criteria) this;
		}

		public Criteria andBetScore5EqualTo(Integer value) {
			addCriterion("bet_score_5 =", value, "betScore5");
			return (Criteria) this;
		}

		public Criteria andBetScore5NotEqualTo(Integer value) {
			addCriterion("bet_score_5 <>", value, "betScore5");
			return (Criteria) this;
		}

		public Criteria andBetScore5GreaterThan(Integer value) {
			addCriterion("bet_score_5 >", value, "betScore5");
			return (Criteria) this;
		}

		public Criteria andBetScore5GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_score_5 >=", value, "betScore5");
			return (Criteria) this;
		}

		public Criteria andBetScore5LessThan(Integer value) {
			addCriterion("bet_score_5 <", value, "betScore5");
			return (Criteria) this;
		}

		public Criteria andBetScore5LessThanOrEqualTo(Integer value) {
			addCriterion("bet_score_5 <=", value, "betScore5");
			return (Criteria) this;
		}

		public Criteria andBetScore5In(List<Integer> values) {
			addCriterion("bet_score_5 in", values, "betScore5");
			return (Criteria) this;
		}

		public Criteria andBetScore5NotIn(List<Integer> values) {
			addCriterion("bet_score_5 not in", values, "betScore5");
			return (Criteria) this;
		}

		public Criteria andBetScore5Between(Integer value1, Integer value2) {
			addCriterion("bet_score_5 between", value1, value2, "betScore5");
			return (Criteria) this;
		}

		public Criteria andBetScore5NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_score_5 not between", value1, value2, "betScore5");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6IsNull() {
			addCriterion("bet_fruit_id_6 is null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6IsNotNull() {
			addCriterion("bet_fruit_id_6 is not null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6EqualTo(Integer value) {
			addCriterion("bet_fruit_id_6 =", value, "betFruitId6");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6NotEqualTo(Integer value) {
			addCriterion("bet_fruit_id_6 <>", value, "betFruitId6");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6GreaterThan(Integer value) {
			addCriterion("bet_fruit_id_6 >", value, "betFruitId6");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_6 >=", value, "betFruitId6");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6LessThan(Integer value) {
			addCriterion("bet_fruit_id_6 <", value, "betFruitId6");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6LessThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_6 <=", value, "betFruitId6");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6In(List<Integer> values) {
			addCriterion("bet_fruit_id_6 in", values, "betFruitId6");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6NotIn(List<Integer> values) {
			addCriterion("bet_fruit_id_6 not in", values, "betFruitId6");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6Between(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_6 between", value1, value2, "betFruitId6");
			return (Criteria) this;
		}

		public Criteria andBetFruitId6NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_6 not between", value1, value2, "betFruitId6");
			return (Criteria) this;
		}

		public Criteria andBetScore6IsNull() {
			addCriterion("bet_score_6 is null");
			return (Criteria) this;
		}

		public Criteria andBetScore6IsNotNull() {
			addCriterion("bet_score_6 is not null");
			return (Criteria) this;
		}

		public Criteria andBetScore6EqualTo(Integer value) {
			addCriterion("bet_score_6 =", value, "betScore6");
			return (Criteria) this;
		}

		public Criteria andBetScore6NotEqualTo(Integer value) {
			addCriterion("bet_score_6 <>", value, "betScore6");
			return (Criteria) this;
		}

		public Criteria andBetScore6GreaterThan(Integer value) {
			addCriterion("bet_score_6 >", value, "betScore6");
			return (Criteria) this;
		}

		public Criteria andBetScore6GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_score_6 >=", value, "betScore6");
			return (Criteria) this;
		}

		public Criteria andBetScore6LessThan(Integer value) {
			addCriterion("bet_score_6 <", value, "betScore6");
			return (Criteria) this;
		}

		public Criteria andBetScore6LessThanOrEqualTo(Integer value) {
			addCriterion("bet_score_6 <=", value, "betScore6");
			return (Criteria) this;
		}

		public Criteria andBetScore6In(List<Integer> values) {
			addCriterion("bet_score_6 in", values, "betScore6");
			return (Criteria) this;
		}

		public Criteria andBetScore6NotIn(List<Integer> values) {
			addCriterion("bet_score_6 not in", values, "betScore6");
			return (Criteria) this;
		}

		public Criteria andBetScore6Between(Integer value1, Integer value2) {
			addCriterion("bet_score_6 between", value1, value2, "betScore6");
			return (Criteria) this;
		}

		public Criteria andBetScore6NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_score_6 not between", value1, value2, "betScore6");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7IsNull() {
			addCriterion("bet_fruit_id_7 is null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7IsNotNull() {
			addCriterion("bet_fruit_id_7 is not null");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7EqualTo(Integer value) {
			addCriterion("bet_fruit_id_7 =", value, "betFruitId7");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7NotEqualTo(Integer value) {
			addCriterion("bet_fruit_id_7 <>", value, "betFruitId7");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7GreaterThan(Integer value) {
			addCriterion("bet_fruit_id_7 >", value, "betFruitId7");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_7 >=", value, "betFruitId7");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7LessThan(Integer value) {
			addCriterion("bet_fruit_id_7 <", value, "betFruitId7");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7LessThanOrEqualTo(Integer value) {
			addCriterion("bet_fruit_id_7 <=", value, "betFruitId7");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7In(List<Integer> values) {
			addCriterion("bet_fruit_id_7 in", values, "betFruitId7");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7NotIn(List<Integer> values) {
			addCriterion("bet_fruit_id_7 not in", values, "betFruitId7");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7Between(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_7 between", value1, value2, "betFruitId7");
			return (Criteria) this;
		}

		public Criteria andBetFruitId7NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_fruit_id_7 not between", value1, value2, "betFruitId7");
			return (Criteria) this;
		}

		public Criteria andBetScore7IsNull() {
			addCriterion("bet_score_7 is null");
			return (Criteria) this;
		}

		public Criteria andBetScore7IsNotNull() {
			addCriterion("bet_score_7 is not null");
			return (Criteria) this;
		}

		public Criteria andBetScore7EqualTo(Integer value) {
			addCriterion("bet_score_7 =", value, "betScore7");
			return (Criteria) this;
		}

		public Criteria andBetScore7NotEqualTo(Integer value) {
			addCriterion("bet_score_7 <>", value, "betScore7");
			return (Criteria) this;
		}

		public Criteria andBetScore7GreaterThan(Integer value) {
			addCriterion("bet_score_7 >", value, "betScore7");
			return (Criteria) this;
		}

		public Criteria andBetScore7GreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_score_7 >=", value, "betScore7");
			return (Criteria) this;
		}

		public Criteria andBetScore7LessThan(Integer value) {
			addCriterion("bet_score_7 <", value, "betScore7");
			return (Criteria) this;
		}

		public Criteria andBetScore7LessThanOrEqualTo(Integer value) {
			addCriterion("bet_score_7 <=", value, "betScore7");
			return (Criteria) this;
		}

		public Criteria andBetScore7In(List<Integer> values) {
			addCriterion("bet_score_7 in", values, "betScore7");
			return (Criteria) this;
		}

		public Criteria andBetScore7NotIn(List<Integer> values) {
			addCriterion("bet_score_7 not in", values, "betScore7");
			return (Criteria) this;
		}

		public Criteria andBetScore7Between(Integer value1, Integer value2) {
			addCriterion("bet_score_7 between", value1, value2, "betScore7");
			return (Criteria) this;
		}

		public Criteria andBetScore7NotBetween(Integer value1, Integer value2) {
			addCriterion("bet_score_7 not between", value1, value2, "betScore7");
			return (Criteria) this;
		}

		public Criteria andBetResultIsNull() {
			addCriterion("bet_result is null");
			return (Criteria) this;
		}

		public Criteria andBetResultIsNotNull() {
			addCriterion("bet_result is not null");
			return (Criteria) this;
		}

		public Criteria andBetResultEqualTo(Integer value) {
			addCriterion("bet_result =", value, "betResult");
			return (Criteria) this;
		}

		public Criteria andBetResultNotEqualTo(Integer value) {
			addCriterion("bet_result <>", value, "betResult");
			return (Criteria) this;
		}

		public Criteria andBetResultGreaterThan(Integer value) {
			addCriterion("bet_result >", value, "betResult");
			return (Criteria) this;
		}

		public Criteria andBetResultGreaterThanOrEqualTo(Integer value) {
			addCriterion("bet_result >=", value, "betResult");
			return (Criteria) this;
		}

		public Criteria andBetResultLessThan(Integer value) {
			addCriterion("bet_result <", value, "betResult");
			return (Criteria) this;
		}

		public Criteria andBetResultLessThanOrEqualTo(Integer value) {
			addCriterion("bet_result <=", value, "betResult");
			return (Criteria) this;
		}

		public Criteria andBetResultIn(List<Integer> values) {
			addCriterion("bet_result in", values, "betResult");
			return (Criteria) this;
		}

		public Criteria andBetResultNotIn(List<Integer> values) {
			addCriterion("bet_result not in", values, "betResult");
			return (Criteria) this;
		}

		public Criteria andBetResultBetween(Integer value1, Integer value2) {
			addCriterion("bet_result between", value1, value2, "betResult");
			return (Criteria) this;
		}

		public Criteria andBetResultNotBetween(Integer value1, Integer value2) {
			addCriterion("bet_result not between", value1, value2, "betResult");
			return (Criteria) this;
		}

		public Criteria andGotScoreIsNull() {
			addCriterion("got_score is null");
			return (Criteria) this;
		}

		public Criteria andGotScoreIsNotNull() {
			addCriterion("got_score is not null");
			return (Criteria) this;
		}

		public Criteria andGotScoreEqualTo(Integer value) {
			addCriterion("got_score =", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreNotEqualTo(Integer value) {
			addCriterion("got_score <>", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreGreaterThan(Integer value) {
			addCriterion("got_score >", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("got_score >=", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreLessThan(Integer value) {
			addCriterion("got_score <", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreLessThanOrEqualTo(Integer value) {
			addCriterion("got_score <=", value, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreIn(List<Integer> values) {
			addCriterion("got_score in", values, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreNotIn(List<Integer> values) {
			addCriterion("got_score not in", values, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreBetween(Integer value1, Integer value2) {
			addCriterion("got_score between", value1, value2, "gotScore");
			return (Criteria) this;
		}

		public Criteria andGotScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("got_score not between", value1, value2, "gotScore");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_machine_bet_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_machine_bet_record
     *
     * @mbg.generated do_not_delete_during_merge Sun Mar 26 16:59:34 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}