package com.ahem.machine.weixin.entity;

import java.util.Date;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table v_user_bet_record
 *
 * @mbg.generated do_not_delete_during_merge Thu Mar 30 10:34:57 CST 2017
 */
public class VUserBetRecord {

	/**
	 * Database Column Remarks: 下注id This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 用户编号 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.user_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Integer userId;
	/**
	 * Database Column Remarks: 开奖期号 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.record_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Integer recordId;
	/**
	 * Database Column Remarks: 下注水果编号 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.bet_fruit_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Integer betFruitId;
	/**
	 * Database Column Remarks: 下注分数 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.bet_score
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Integer betScore;
	/**
	 * Database Column Remarks: 下注倍数 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.bet_multiple
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Integer betMultiple;
	/**
	 * Database Column Remarks: 下注时间 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.bet_time
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Date betTime;
	/**
	 * Database Column Remarks: 开奖号码(对应位置表的编号) This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.open_number
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Integer openNumber;
	/**
	 * Database Column Remarks: 水果编号 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.open_fruit_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Integer openFruitId;
	/**
	 * Database Column Remarks: 英文名称 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.open_fruit_en_name
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private String openFruitEnName;
	/**
	 * Database Column Remarks: 中文名称 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.open_fruit_cn_name
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private String openFruitCnName;
	/**
	 * Database Column Remarks: 水果倍数 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.open_fruit_multiple
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Integer openFruitMultiple;
	/**
	 * Database Column Remarks: 开奖时间 This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.open_time
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private Date openTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.bet_result
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private String betResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_user_bet_record.got_score
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	private BigDecimal gotScore;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.id
	 * @return  the value of v_user_bet_record.id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.id
	 * @param id  the value for v_user_bet_record.id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.user_id
	 * @return  the value of v_user_bet_record.user_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.user_id
	 * @param userId  the value for v_user_bet_record.user_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.record_id
	 * @return  the value of v_user_bet_record.record_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Integer getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.record_id
	 * @param recordId  the value for v_user_bet_record.record_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.bet_fruit_id
	 * @return  the value of v_user_bet_record.bet_fruit_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Integer getBetFruitId() {
		return betFruitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.bet_fruit_id
	 * @param betFruitId  the value for v_user_bet_record.bet_fruit_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setBetFruitId(Integer betFruitId) {
		this.betFruitId = betFruitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.bet_score
	 * @return  the value of v_user_bet_record.bet_score
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Integer getBetScore() {
		return betScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.bet_score
	 * @param betScore  the value for v_user_bet_record.bet_score
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setBetScore(Integer betScore) {
		this.betScore = betScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.bet_multiple
	 * @return  the value of v_user_bet_record.bet_multiple
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Integer getBetMultiple() {
		return betMultiple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.bet_multiple
	 * @param betMultiple  the value for v_user_bet_record.bet_multiple
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setBetMultiple(Integer betMultiple) {
		this.betMultiple = betMultiple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.bet_time
	 * @return  the value of v_user_bet_record.bet_time
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Date getBetTime() {
		return betTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.bet_time
	 * @param betTime  the value for v_user_bet_record.bet_time
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setBetTime(Date betTime) {
		this.betTime = betTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.open_number
	 * @return  the value of v_user_bet_record.open_number
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Integer getOpenNumber() {
		return openNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.open_number
	 * @param openNumber  the value for v_user_bet_record.open_number
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setOpenNumber(Integer openNumber) {
		this.openNumber = openNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.open_fruit_id
	 * @return  the value of v_user_bet_record.open_fruit_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Integer getOpenFruitId() {
		return openFruitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.open_fruit_id
	 * @param openFruitId  the value for v_user_bet_record.open_fruit_id
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setOpenFruitId(Integer openFruitId) {
		this.openFruitId = openFruitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.open_fruit_en_name
	 * @return  the value of v_user_bet_record.open_fruit_en_name
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public String getOpenFruitEnName() {
		return openFruitEnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.open_fruit_en_name
	 * @param openFruitEnName  the value for v_user_bet_record.open_fruit_en_name
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setOpenFruitEnName(String openFruitEnName) {
		this.openFruitEnName = openFruitEnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.open_fruit_cn_name
	 * @return  the value of v_user_bet_record.open_fruit_cn_name
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public String getOpenFruitCnName() {
		return openFruitCnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.open_fruit_cn_name
	 * @param openFruitCnName  the value for v_user_bet_record.open_fruit_cn_name
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setOpenFruitCnName(String openFruitCnName) {
		this.openFruitCnName = openFruitCnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.open_fruit_multiple
	 * @return  the value of v_user_bet_record.open_fruit_multiple
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Integer getOpenFruitMultiple() {
		return openFruitMultiple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.open_fruit_multiple
	 * @param openFruitMultiple  the value for v_user_bet_record.open_fruit_multiple
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setOpenFruitMultiple(Integer openFruitMultiple) {
		this.openFruitMultiple = openFruitMultiple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.open_time
	 * @return  the value of v_user_bet_record.open_time
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public Date getOpenTime() {
		return openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.open_time
	 * @param openTime  the value for v_user_bet_record.open_time
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.bet_result
	 * @return  the value of v_user_bet_record.bet_result
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public String getBetResult() {
		return betResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.bet_result
	 * @param betResult  the value for v_user_bet_record.bet_result
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setBetResult(String betResult) {
		this.betResult = betResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_user_bet_record.got_score
	 * @return  the value of v_user_bet_record.got_score
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public BigDecimal getGotScore() {
		return gotScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_user_bet_record.got_score
	 * @param gotScore  the value for v_user_bet_record.got_score
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	public void setGotScore(BigDecimal gotScore) {
		this.gotScore = gotScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_user_bet_record
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", userId=").append(userId);
		sb.append(", recordId=").append(recordId);
		sb.append(", betFruitId=").append(betFruitId);
		sb.append(", betScore=").append(betScore);
		sb.append(", betMultiple=").append(betMultiple);
		sb.append(", betTime=").append(betTime);
		sb.append(", openNumber=").append(openNumber);
		sb.append(", openFruitId=").append(openFruitId);
		sb.append(", openFruitEnName=").append(openFruitEnName);
		sb.append(", openFruitCnName=").append(openFruitCnName);
		sb.append(", openFruitMultiple=").append(openFruitMultiple);
		sb.append(", openTime=").append(openTime);
		sb.append(", betResult=").append(betResult);
		sb.append(", gotScore=").append(gotScore);
		sb.append("]");
		return sb.toString();
	}
}