package com.ahem.machine.weixin.mapper;

import com.ahem.machine.weixin.entity.TMachineUser;
import com.ahem.machine.weixin.entity.TMachineUserExample.Criteria;
import com.ahem.machine.weixin.entity.TMachineUserExample.Criterion;
import com.ahem.machine.weixin.entity.TMachineUserExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TMachineUserSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_user
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String countByExample(TMachineUserExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("t_machine_user");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_user
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String deleteByExample(TMachineUserExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("t_machine_user");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_user
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String insertSelective(TMachineUser record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("t_machine_user");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=INTEGER}");
		}
		if (record.getUserName() != null) {
			sql.VALUES("user_name", "#{userName,jdbcType=VARCHAR}");
		}
		if (record.getPassword() != null) {
			sql.VALUES("password", "#{password,jdbcType=VARCHAR}");
		}
		if (record.getMobileNum() != null) {
			sql.VALUES("mobile_num", "#{mobileNum,jdbcType=INTEGER}");
		}
		if (record.getWeixinOpenId() != null) {
			sql.VALUES("weixin_open_id", "#{weixinOpenId,jdbcType=VARCHAR}");
		}
		if (record.getCreateTime() != null) {
			sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
		}
		if (record.getLoginTime() != null) {
			sql.VALUES("login_time", "#{loginTime,jdbcType=TIMESTAMP}");
		}
		if (record.getScore() != null) {
			sql.VALUES("score", "#{score,jdbcType=INTEGER}");
		}
		if (record.getNickname() != null) {
			sql.VALUES("nickname", "#{nickname,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_user
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String selectByExample(TMachineUserExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("user_name");
		sql.SELECT("password");
		sql.SELECT("mobile_num");
		sql.SELECT("weixin_open_id");
		sql.SELECT("create_time");
		sql.SELECT("login_time");
		sql.SELECT("score");
		sql.SELECT("nickname");
		sql.FROM("t_machine_user");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_user
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		TMachineUser record = (TMachineUser) parameter.get("record");
		TMachineUserExample example = (TMachineUserExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("t_machine_user");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=INTEGER}");
		}
		if (record.getUserName() != null) {
			sql.SET("user_name = #{record.userName,jdbcType=VARCHAR}");
		}
		if (record.getPassword() != null) {
			sql.SET("password = #{record.password,jdbcType=VARCHAR}");
		}
		if (record.getMobileNum() != null) {
			sql.SET("mobile_num = #{record.mobileNum,jdbcType=INTEGER}");
		}
		if (record.getWeixinOpenId() != null) {
			sql.SET("weixin_open_id = #{record.weixinOpenId,jdbcType=VARCHAR}");
		}
		if (record.getCreateTime() != null) {
			sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
		}
		if (record.getLoginTime() != null) {
			sql.SET("login_time = #{record.loginTime,jdbcType=TIMESTAMP}");
		}
		if (record.getScore() != null) {
			sql.SET("score = #{record.score,jdbcType=INTEGER}");
		}
		if (record.getNickname() != null) {
			sql.SET("nickname = #{record.nickname,jdbcType=VARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_user
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("t_machine_user");
		sql.SET("id = #{record.id,jdbcType=INTEGER}");
		sql.SET("user_name = #{record.userName,jdbcType=VARCHAR}");
		sql.SET("password = #{record.password,jdbcType=VARCHAR}");
		sql.SET("mobile_num = #{record.mobileNum,jdbcType=INTEGER}");
		sql.SET("weixin_open_id = #{record.weixinOpenId,jdbcType=VARCHAR}");
		sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
		sql.SET("login_time = #{record.loginTime,jdbcType=TIMESTAMP}");
		sql.SET("score = #{record.score,jdbcType=INTEGER}");
		sql.SET("nickname = #{record.nickname,jdbcType=VARCHAR}");
		TMachineUserExample example = (TMachineUserExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_user
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	public String updateByPrimaryKeySelective(TMachineUser record) {
		SQL sql = new SQL();
		sql.UPDATE("t_machine_user");
		if (record.getUserName() != null) {
			sql.SET("user_name = #{userName,jdbcType=VARCHAR}");
		}
		if (record.getPassword() != null) {
			sql.SET("password = #{password,jdbcType=VARCHAR}");
		}
		if (record.getMobileNum() != null) {
			sql.SET("mobile_num = #{mobileNum,jdbcType=INTEGER}");
		}
		if (record.getWeixinOpenId() != null) {
			sql.SET("weixin_open_id = #{weixinOpenId,jdbcType=VARCHAR}");
		}
		if (record.getCreateTime() != null) {
			sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
		}
		if (record.getLoginTime() != null) {
			sql.SET("login_time = #{loginTime,jdbcType=TIMESTAMP}");
		}
		if (record.getScore() != null) {
			sql.SET("score = #{score,jdbcType=INTEGER}");
		}
		if (record.getNickname() != null) {
			sql.SET("nickname = #{nickname,jdbcType=VARCHAR}");
		}
		sql.WHERE("id = #{id,jdbcType=INTEGER}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_user
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	protected void applyWhere(SQL sql, TMachineUserExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}