package com.ahem.machine.weixin.mapper;

import com.ahem.machine.weixin.entity.TMachineFruit;
import com.ahem.machine.weixin.entity.TMachineFruitExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface TMachineFruitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@SelectProvider(type = TMachineFruitSqlProvider.class, method = "countByExample")
	long countByExample(TMachineFruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@DeleteProvider(type = TMachineFruitSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TMachineFruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@Delete({ "delete from t_machine_fruit", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@Insert({ "insert into t_machine_fruit (id, en_name, ", "cn_name, image_name, ", "button_name)",
			"values (#{id,jdbcType=INTEGER}, #{enName,jdbcType=VARCHAR}, ",
			"#{cnName,jdbcType=VARCHAR}, #{imageName,jdbcType=VARCHAR}, ", "#{buttonName,jdbcType=VARCHAR})" })
	int insert(TMachineFruit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@InsertProvider(type = TMachineFruitSqlProvider.class, method = "insertSelective")
	int insertSelective(TMachineFruit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@SelectProvider(type = TMachineFruitSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "en_name", property = "enName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "cn_name", property = "cnName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "image_name", property = "imageName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "button_name", property = "buttonName", jdbcType = JdbcType.VARCHAR) })
	List<TMachineFruit> selectByExample(TMachineFruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@Select({ "select", "id, en_name, cn_name, image_name, button_name", "from t_machine_fruit",
			"where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "en_name", property = "enName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "cn_name", property = "cnName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "image_name", property = "imageName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "button_name", property = "buttonName", jdbcType = JdbcType.VARCHAR) })
	TMachineFruit selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@UpdateProvider(type = TMachineFruitSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TMachineFruit record, @Param("example") TMachineFruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@UpdateProvider(type = TMachineFruitSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TMachineFruit record, @Param("example") TMachineFruitExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@UpdateProvider(type = TMachineFruitSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TMachineFruit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_fruit
	 * @mbg.generated  Sun Mar 26 16:59:34 CST 2017
	 */
	@Update({ "update t_machine_fruit", "set en_name = #{enName,jdbcType=VARCHAR},",
			"cn_name = #{cnName,jdbcType=VARCHAR},", "image_name = #{imageName,jdbcType=VARCHAR},",
			"button_name = #{buttonName,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(TMachineFruit record);
}