package com.ahem.machine.weixin.mapper;

import com.ahem.machine.weixin.entity.TMachineBigSmallRecord;
import com.ahem.machine.weixin.entity.TMachineBigSmallRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface TMachineBigSmallRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@SelectProvider(type = TMachineBigSmallRecordSqlProvider.class, method = "countByExample")
	long countByExample(TMachineBigSmallRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@DeleteProvider(type = TMachineBigSmallRecordSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TMachineBigSmallRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@Delete({ "delete from t_machine_big_small_record", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@Insert({ "insert into t_machine_big_small_record (id, record_id, ", "user_id, big_small_num, ",
			"bet_num, bet_time, ", "bet_score, got_score)",
			"values (#{id,jdbcType=INTEGER}, #{recordId,jdbcType=INTEGER}, ",
			"#{userId,jdbcType=INTEGER}, #{bigSmallNum,jdbcType=INTEGER}, ",
			"#{betNum,jdbcType=INTEGER}, #{betTime,jdbcType=TIMESTAMP}, ",
			"#{betScore,jdbcType=INTEGER}, #{gotScore,jdbcType=INTEGER})" })
	int insert(TMachineBigSmallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@InsertProvider(type = TMachineBigSmallRecordSqlProvider.class, method = "insertSelective")
	int insertSelective(TMachineBigSmallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@SelectProvider(type = TMachineBigSmallRecordSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "record_id", property = "recordId", jdbcType = JdbcType.INTEGER),
			@Result(column = "user_id", property = "userId", jdbcType = JdbcType.INTEGER),
			@Result(column = "big_small_num", property = "bigSmallNum", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_num", property = "betNum", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_time", property = "betTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "bet_score", property = "betScore", jdbcType = JdbcType.INTEGER),
			@Result(column = "got_score", property = "gotScore", jdbcType = JdbcType.INTEGER) })
	List<TMachineBigSmallRecord> selectByExampleWithRowbounds(TMachineBigSmallRecordExample example,
			RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@SelectProvider(type = TMachineBigSmallRecordSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "record_id", property = "recordId", jdbcType = JdbcType.INTEGER),
			@Result(column = "user_id", property = "userId", jdbcType = JdbcType.INTEGER),
			@Result(column = "big_small_num", property = "bigSmallNum", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_num", property = "betNum", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_time", property = "betTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "bet_score", property = "betScore", jdbcType = JdbcType.INTEGER),
			@Result(column = "got_score", property = "gotScore", jdbcType = JdbcType.INTEGER) })
	List<TMachineBigSmallRecord> selectByExample(TMachineBigSmallRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@Select({ "select", "id, record_id, user_id, big_small_num, bet_num, bet_time, bet_score, got_score",
			"from t_machine_big_small_record", "where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "record_id", property = "recordId", jdbcType = JdbcType.INTEGER),
			@Result(column = "user_id", property = "userId", jdbcType = JdbcType.INTEGER),
			@Result(column = "big_small_num", property = "bigSmallNum", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_num", property = "betNum", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_time", property = "betTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "bet_score", property = "betScore", jdbcType = JdbcType.INTEGER),
			@Result(column = "got_score", property = "gotScore", jdbcType = JdbcType.INTEGER) })
	TMachineBigSmallRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@UpdateProvider(type = TMachineBigSmallRecordSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TMachineBigSmallRecord record,
			@Param("example") TMachineBigSmallRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@UpdateProvider(type = TMachineBigSmallRecordSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TMachineBigSmallRecord record,
			@Param("example") TMachineBigSmallRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@UpdateProvider(type = TMachineBigSmallRecordSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TMachineBigSmallRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_big_small_record
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@Update({ "update t_machine_big_small_record", "set record_id = #{recordId,jdbcType=INTEGER},",
			"user_id = #{userId,jdbcType=INTEGER},", "big_small_num = #{bigSmallNum,jdbcType=INTEGER},",
			"bet_num = #{betNum,jdbcType=INTEGER},", "bet_time = #{betTime,jdbcType=TIMESTAMP},",
			"bet_score = #{betScore,jdbcType=INTEGER},", "got_score = #{gotScore,jdbcType=INTEGER}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(TMachineBigSmallRecord record);
}