package com.ahem.machine.weixin.mapper;

import com.ahem.machine.weixin.entity.TMachineIndex;
import com.ahem.machine.weixin.entity.TMachineIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TMachineIndexMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@SelectProvider(type = TMachineIndexSqlProvider.class, method = "countByExample")
	long countByExample(TMachineIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@DeleteProvider(type = TMachineIndexSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TMachineIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@Delete({ "delete from t_machine_index", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@Insert({ "insert into t_machine_index (id, fruit_id)",
			"values (#{id,jdbcType=INTEGER}, #{fruitId,jdbcType=INTEGER})" })
	int insert(TMachineIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@InsertProvider(type = TMachineIndexSqlProvider.class, method = "insertSelective")
	int insertSelective(TMachineIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@SelectProvider(type = TMachineIndexSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "fruit_id", property = "fruitId", jdbcType = JdbcType.INTEGER) })
	List<TMachineIndex> selectByExampleWithRowbounds(TMachineIndexExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@SelectProvider(type = TMachineIndexSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "fruit_id", property = "fruitId", jdbcType = JdbcType.INTEGER) })
	List<TMachineIndex> selectByExample(TMachineIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@Select({ "select", "id, fruit_id", "from t_machine_index", "where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "fruit_id", property = "fruitId", jdbcType = JdbcType.INTEGER) })
	TMachineIndex selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@UpdateProvider(type = TMachineIndexSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TMachineIndex record, @Param("example") TMachineIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@UpdateProvider(type = TMachineIndexSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TMachineIndex record, @Param("example") TMachineIndexExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@UpdateProvider(type = TMachineIndexSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TMachineIndex record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_index
	 * @mbg.generated  Fri Apr 07 09:38:56 CST 2017
	 */
	@Update({ "update t_machine_index", "set fruit_id = #{fruitId,jdbcType=INTEGER}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(TMachineIndex record);
}