package com.ahem.machine.weixin.mapper;

import com.ahem.machine.weixin.entity.TMachineRecord;
import com.ahem.machine.weixin.entity.TMachineRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface TMachineRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@SelectProvider(type = TMachineRecordSqlProvider.class, method = "countByExample")
	long countByExample(TMachineRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@DeleteProvider(type = TMachineRecordSqlProvider.class, method = "deleteByExample")
	int deleteByExample(TMachineRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@Delete({ "delete from t_machine_record", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@Insert({ "insert into t_machine_record (open_time, open_number)",
			"values (#{openTime,jdbcType=TIMESTAMP}, #{openNumber,jdbcType=INTEGER})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insert(TMachineRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@InsertProvider(type = TMachineRecordSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insertSelective(TMachineRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@SelectProvider(type = TMachineRecordSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "open_time", property = "openTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "open_number", property = "openNumber", jdbcType = JdbcType.INTEGER) })
	List<TMachineRecord> selectByExampleWithRowbounds(TMachineRecordExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@SelectProvider(type = TMachineRecordSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "open_time", property = "openTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "open_number", property = "openNumber", jdbcType = JdbcType.INTEGER) })
	List<TMachineRecord> selectByExample(TMachineRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@Select({ "select", "id, open_time, open_number", "from t_machine_record", "where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "open_time", property = "openTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "open_number", property = "openNumber", jdbcType = JdbcType.INTEGER) })
	TMachineRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@UpdateProvider(type = TMachineRecordSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") TMachineRecord record,
			@Param("example") TMachineRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@UpdateProvider(type = TMachineRecordSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") TMachineRecord record, @Param("example") TMachineRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@UpdateProvider(type = TMachineRecordSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TMachineRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_machine_record
	 * @mbg.generated  Thu Apr 06 14:16:55 CST 2017
	 */
	@Update({ "update t_machine_record", "set open_time = #{openTime,jdbcType=TIMESTAMP},",
			"open_number = #{openNumber,jdbcType=INTEGER}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(TMachineRecord record);
}