package com.ahem.machine.weixin.mapper;

import com.ahem.machine.weixin.entity.VBetStatistic;
import com.ahem.machine.weixin.entity.VBetStatisticExample;
import java.util.List;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface VBetStatisticMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_bet_statistic
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@SelectProvider(type = VBetStatisticSqlProvider.class, method = "countByExample")
	long countByExample(VBetStatisticExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_bet_statistic
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@SelectProvider(type = VBetStatisticSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "record_id", property = "recordId", jdbcType = JdbcType.INTEGER),
			@Result(column = "fruit_id", property = "fruitId", jdbcType = JdbcType.INTEGER),
			@Result(column = "fruit_name", property = "fruitName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "sum_score", property = "sumScore", jdbcType = JdbcType.DECIMAL),
			@Result(column = "all_sum", property = "allSum", jdbcType = JdbcType.DECIMAL) })
	List<VBetStatistic> selectByExampleWithRowbounds(VBetStatisticExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_bet_statistic
	 * @mbg.generated  Sat Apr 15 20:14:12 CST 2017
	 */
	@SelectProvider(type = VBetStatisticSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "record_id", property = "recordId", jdbcType = JdbcType.INTEGER),
			@Result(column = "fruit_id", property = "fruitId", jdbcType = JdbcType.INTEGER),
			@Result(column = "fruit_name", property = "fruitName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "sum_score", property = "sumScore", jdbcType = JdbcType.DECIMAL),
			@Result(column = "all_sum", property = "allSum", jdbcType = JdbcType.DECIMAL) })
	List<VBetStatistic> selectByExample(VBetStatisticExample example);
}