package com.ahem.machine.weixin.mapper;

import com.ahem.machine.weixin.entity.VUserBetRecord;
import com.ahem.machine.weixin.entity.VUserBetRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.apache.ibatis.session.RowBounds;

public interface VUserBetRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_user_bet_record
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	@SelectProvider(type = VUserBetRecordSqlProvider.class, method = "countByExample")
	long countByExample(VUserBetRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_user_bet_record
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	@SelectProvider(type = VUserBetRecordSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER),
			@Result(column = "user_id", property = "userId", jdbcType = JdbcType.INTEGER),
			@Result(column = "record_id", property = "recordId", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_fruit_id", property = "betFruitId", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_score", property = "betScore", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_multiple", property = "betMultiple", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_time", property = "betTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "open_number", property = "openNumber", jdbcType = JdbcType.INTEGER),
			@Result(column = "open_fruit_id", property = "openFruitId", jdbcType = JdbcType.INTEGER),
			@Result(column = "open_fruit_en_name", property = "openFruitEnName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "open_fruit_cn_name", property = "openFruitCnName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "open_fruit_multiple", property = "openFruitMultiple", jdbcType = JdbcType.INTEGER),
			@Result(column = "open_time", property = "openTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "bet_result", property = "betResult", jdbcType = JdbcType.VARCHAR),
			@Result(column = "got_score", property = "gotScore", jdbcType = JdbcType.DECIMAL) })
	List<VUserBetRecord> selectByExampleWithRowbounds(VUserBetRecordExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_user_bet_record
	 * @mbg.generated  Thu Mar 30 14:53:28 CST 2017
	 */
	@SelectProvider(type = VUserBetRecordSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER),
			@Result(column = "user_id", property = "userId", jdbcType = JdbcType.INTEGER),
			@Result(column = "record_id", property = "recordId", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_fruit_id", property = "betFruitId", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_score", property = "betScore", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_multiple", property = "betMultiple", jdbcType = JdbcType.INTEGER),
			@Result(column = "bet_time", property = "betTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "open_number", property = "openNumber", jdbcType = JdbcType.INTEGER),
			@Result(column = "open_fruit_id", property = "openFruitId", jdbcType = JdbcType.INTEGER),
			@Result(column = "open_fruit_en_name", property = "openFruitEnName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "open_fruit_cn_name", property = "openFruitCnName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "open_fruit_multiple", property = "openFruitMultiple", jdbcType = JdbcType.INTEGER),
			@Result(column = "open_time", property = "openTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "bet_result", property = "betResult", jdbcType = JdbcType.VARCHAR),
			@Result(column = "got_score", property = "gotScore", jdbcType = JdbcType.DECIMAL) })
	List<VUserBetRecord> selectByExample(VUserBetRecordExample example);
}